services:
  phalcon-mailer-8.1:
    build: docker/8.1
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    depends_on:
      - mailpit

  phalcon-mailer-8.4:
    build: docker/8.4
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
